
export const translations = {
  ar: {
    title: "ماركت ماستر",
    dashboard: "لوحة القيادة",
    products: "المنتجات",
    catalog: "الكتالوج",
    history: "السجل",
    stats: "الإحصائيات",
    cart: "السلة",
    settings: "الإعدادات",
    addProduct: "إضافة منتج",
    editProduct: "تعديل المنتج",
    deleteProduct: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    name: "الاسم",
    price: "السعر الأساسي",
    discountPrice: "سعر الخصم",
    category: "الفئة",
    stock: "المخزون الأساسي",
    description: "الوصف",
    image: "الصورة",
    import: "استيراد JSON",
    export: "تصدير JSON",
    whatsappOrder: "طلب عبر واتساب",
    total: "المجموع",
    checkout: "إتمام الطلب",
    emptyCart: "السلة فارغة",
    noProducts: "لا توجد منتجات حالياً",
    search: "بحث عن منتج...",
    recentActions: "أحدث العمليات",
    stockAlert: "تنبيه المخزون",
    revenue: "الإيرادات المتوقعة",
    totalProducts: "إجمالي المنتجات",
    lowStock: "مخزون منخفض",
    successImport: "تم الاستيراد بنجاح",
    confirmDelete: "هل أنت متأكد من الحذف؟",
    variations: "الخيارات (المقاس، اللون، إلخ)",
    addVariation: "إضافة خيار",
    variationName: "اسم الخيار",
    currency: "أوقية",
    selectVariation: "اختر خياراً",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    password: "كلمة المرور",
    changePassword: "تغيير كلمة المرور",
    oldPassword: "كلمة المرور القديمة",
    newPassword: "كلمة المرور الجديدة",
    wrongPassword: "كلمة مرور خاطئة",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    adminAccess: "دخول المشرف"
  },
  fr: {
    title: "MarketMaster",
    dashboard: "Tableau de bord",
    products: "Produits",
    catalog: "Catalogue",
    history: "Historique",
    stats: "Statistiques",
    cart: "Panier",
    settings: "Paramètres",
    addProduct: "Ajouter Produit",
    editProduct: "Modifier Produit",
    deleteProduct: "Supprimer",
    save: "Enregistrer",
    cancel: "Annuler",
    name: "Nom",
    price: "Prix de base",
    discountPrice: "Prix Promo",
    category: "Catégorie",
    stock: "Stock de base",
    description: "Description",
    image: "Image",
    import: "Importer JSON",
    export: "Exporter JSON",
    whatsappOrder: "Commander via WhatsApp",
    total: "Total",
    checkout: "Passer commande",
    emptyCart: "Le panier est vide",
    noProducts: "Aucun produit disponible",
    search: "Rechercher...",
    recentActions: "Actions récentes",
    stockAlert: "Alerte Stock",
    revenue: "Revenu Estimé",
    totalProducts: "Total Produits",
    lowStock: "Stock Faible",
    successImport: "Importation réussie",
    confirmDelete: "Confirmer la suppression ?",
    variations: "Variations (Taille, Couleur, etc.)",
    addVariation: "Ajouter une variation",
    variationName: "Nom de la variation",
    currency: "MRU",
    selectVariation: "Sélectionner une option",
    login: "Connexion",
    logout: "Déconnexion",
    password: "Mot de passe",
    changePassword: "Changer le mot de passe",
    oldPassword: "Ancien mot de passe",
    newPassword: "Nouveau mot de passe",
    wrongPassword: "Mot de passe incorrect",
    passwordChanged: "Mot de passe changé avec succès",
    adminAccess: "Accès Administrateur"
  }
};
